# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eeg_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 1003)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EEGFilesList = QtWidgets.QListWidget(self.centralwidget)
        self.EEGFilesList.setGeometry(QtCore.QRect(610, 60, 391, 231))
        self.EEGFilesList.setObjectName("EEGFilesList")
        self.TextBrowserMontageInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserMontageInfo.setGeometry(QtCore.QRect(610, 320, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TextBrowserMontageInfo.setFont(font)
        self.TextBrowserMontageInfo.setObjectName("TextBrowserMontageInfo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 300, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PushButtonDeleteMontage = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonDeleteMontage.setGeometry(QtCore.QRect(1010, 360, 93, 28))
        self.PushButtonDeleteMontage.setObjectName("PushButtonDeleteMontage")
        self.TextBrowserComment = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserComment.setGeometry(QtCore.QRect(30, 870, 1071, 81))
        self.TextBrowserComment.setObjectName("TextBrowserComment")
        self.PushButtonRawPlot = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonRawPlot.setGeometry(QtCore.QRect(220, 840, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PushButtonRawPlot.setFont(font)
        self.PushButtonRawPlot.setObjectName("PushButtonRawPlot")
        self.InfoTable = QtWidgets.QTableWidget(self.centralwidget)
        self.InfoTable.setGeometry(QtCore.QRect(610, 510, 491, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoTable.sizePolicy().hasHeightForWidth())
        self.InfoTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.InfoTable.setFont(font)
        self.InfoTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InfoTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.InfoTable.setShowGrid(False)
        self.InfoTable.setRowCount(7)
        self.InfoTable.setColumnCount(2)
        self.InfoTable.setObjectName("InfoTable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.InfoTable.setItem(5, 1, item)
        self.InfoTable.horizontalHeader().setVisible(False)
        self.InfoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.InfoTable.horizontalHeader().setDefaultSectionSize(244)
        self.InfoTable.horizontalHeader().setHighlightSections(True)
        self.InfoTable.verticalHeader().setVisible(False)
        self.InfoTable.verticalHeader().setDefaultSectionSize(35)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 490, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PushButtonPlotPW = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonPlotPW.setGeometry(QtCore.QRect(400, 840, 161, 28))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonPlotPW.setFont(font)
        self.PushButtonPlotPW.setObjectName("PushButtonPlotPW")
        self.PushButtonSaveFif = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonSaveFif.setGeometry(QtCore.QRect(832, 840, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonSaveFif.setFont(font)
        self.PushButtonSaveFif.setObjectName("PushButtonSaveFif")
        self.PushButtonSaveSet = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonSaveSet.setGeometry(QtCore.QRect(970, 840, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonSaveSet.setFont(font)
        self.PushButtonSaveSet.setObjectName("PushButtonSaveSet")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 571, 821))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 575, 775))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButtonADDOrg = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonADDOrg.sizePolicy().hasHeightForWidth())
        self.PushButtonADDOrg.setSizePolicy(sizePolicy)
        self.PushButtonADDOrg.setObjectName("PushButtonADDOrg")
        self.verticalLayout.addWidget(self.PushButtonADDOrg)
        self.PushButtonMontage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonMontage.sizePolicy().hasHeightForWidth())
        self.PushButtonMontage.setSizePolicy(sizePolicy)
        self.PushButtonMontage.setObjectName("PushButtonMontage")
        self.verticalLayout.addWidget(self.PushButtonMontage)
        self.PushButtonInput = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonInput.sizePolicy().hasHeightForWidth())
        self.PushButtonInput.setSizePolicy(sizePolicy)
        self.PushButtonInput.setObjectName("PushButtonInput")
        self.verticalLayout.addWidget(self.PushButtonInput)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PushButtonRename = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonRename.sizePolicy().hasHeightForWidth())
        self.PushButtonRename.setSizePolicy(sizePolicy)
        self.PushButtonRename.setObjectName("PushButtonRename")
        self.verticalLayout_5.addWidget(self.PushButtonRename)
        self.PushButtonReorder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonReorder.sizePolicy().hasHeightForWidth())
        self.PushButtonReorder.setSizePolicy(sizePolicy)
        self.PushButtonReorder.setObjectName("PushButtonReorder")
        self.verticalLayout_5.addWidget(self.PushButtonReorder)
        self.PushButtonNoREF = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonNoREF.sizePolicy().hasHeightForWidth())
        self.PushButtonNoREF.setSizePolicy(sizePolicy)
        self.PushButtonNoREF.setObjectName("PushButtonNoREF")
        self.verticalLayout_5.addWidget(self.PushButtonNoREF)
        self.PushButtonFiltering = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonFiltering.sizePolicy().hasHeightForWidth())
        self.PushButtonFiltering.setSizePolicy(sizePolicy)
        self.PushButtonFiltering.setObjectName("PushButtonFiltering")
        self.verticalLayout_5.addWidget(self.PushButtonFiltering)
        self.PushButtonResampling = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonResampling.sizePolicy().hasHeightForWidth())
        self.PushButtonResampling.setSizePolicy(sizePolicy)
        self.PushButtonResampling.setObjectName("PushButtonResampling")
        self.verticalLayout_5.addWidget(self.PushButtonResampling)
        self.PushButtonDrop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonDrop.sizePolicy().hasHeightForWidth())
        self.PushButtonDrop.setSizePolicy(sizePolicy)
        self.PushButtonDrop.setObjectName("PushButtonDrop")
        self.verticalLayout_5.addWidget(self.PushButtonDrop)
        self.PushButtonEOGO = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonEOGO.sizePolicy().hasHeightForWidth())
        self.PushButtonEOGO.setSizePolicy(sizePolicy)
        self.PushButtonEOGO.setObjectName("PushButtonEOGO")
        self.verticalLayout_5.addWidget(self.PushButtonEOGO)
        self.PushButtonSM = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSM.sizePolicy().hasHeightForWidth())
        self.PushButtonSM.setSizePolicy(sizePolicy)
        self.PushButtonSM.setObjectName("PushButtonSM")
        self.verticalLayout_5.addWidget(self.PushButtonSM)
        self.PushButtonInterP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonInterP.sizePolicy().hasHeightForWidth())
        self.PushButtonInterP.setSizePolicy(sizePolicy)
        self.PushButtonInterP.setObjectName("PushButtonInterP")
        self.verticalLayout_5.addWidget(self.PushButtonInterP)
        self.PushButtonICA = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonICA.sizePolicy().hasHeightForWidth())
        self.PushButtonICA.setSizePolicy(sizePolicy)
        self.PushButtonICA.setObjectName("PushButtonICA")
        self.verticalLayout_5.addWidget(self.PushButtonICA)
        self.PushButtonApplyICA = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonApplyICA.sizePolicy().hasHeightForWidth())
        self.PushButtonApplyICA.setSizePolicy(sizePolicy)
        self.PushButtonApplyICA.setObjectName("PushButtonApplyICA")
        self.verticalLayout_5.addWidget(self.PushButtonApplyICA)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PushButtonSplit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSplit.sizePolicy().hasHeightForWidth())
        self.PushButtonSplit.setSizePolicy(sizePolicy)
        self.PushButtonSplit.setObjectName("PushButtonSplit")
        self.verticalLayout_6.addWidget(self.PushButtonSplit)
        self.PushButtonSelectEOG = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSelectEOG.sizePolicy().hasHeightForWidth())
        self.PushButtonSelectEOG.setSizePolicy(sizePolicy)
        self.PushButtonSelectEOG.setObjectName("PushButtonSelectEOG")
        self.verticalLayout_6.addWidget(self.PushButtonSelectEOG)
        self.PushButtonSMHP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSMHP.sizePolicy().hasHeightForWidth())
        self.PushButtonSMHP.setSizePolicy(sizePolicy)
        self.PushButtonSMHP.setObjectName("PushButtonSMHP")
        self.verticalLayout_6.addWidget(self.PushButtonSMHP)
        self.PushButtonInterPHP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonInterPHP.sizePolicy().hasHeightForWidth())
        self.PushButtonInterPHP.setSizePolicy(sizePolicy)
        self.PushButtonInterPHP.setObjectName("PushButtonInterPHP")
        self.verticalLayout_6.addWidget(self.PushButtonInterPHP)
        self.PushButtonAdjust = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonAdjust.sizePolicy().hasHeightForWidth())
        self.PushButtonAdjust.setSizePolicy(sizePolicy)
        self.PushButtonAdjust.setObjectName("PushButtonAdjust")
        self.verticalLayout_6.addWidget(self.PushButtonAdjust)
        self.PushButtonEOGCorrect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonEOGCorrect.sizePolicy().hasHeightForWidth())
        self.PushButtonEOGCorrect.setSizePolicy(sizePolicy)
        self.PushButtonEOGCorrect.setObjectName("PushButtonEOGCorrect")
        self.verticalLayout_6.addWidget(self.PushButtonEOGCorrect)
        self.PushButtonCSD = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonCSD.sizePolicy().hasHeightForWidth())
        self.PushButtonCSD.setSizePolicy(sizePolicy)
        self.PushButtonCSD.setObjectName("PushButtonCSD")
        self.verticalLayout_6.addWidget(self.PushButtonCSD)
        self.PushButtonMerge = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonMerge.sizePolicy().hasHeightForWidth())
        self.PushButtonMerge.setSizePolicy(sizePolicy)
        self.PushButtonMerge.setObjectName("PushButtonMerge")
        self.verticalLayout_6.addWidget(self.PushButtonMerge)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 9, 551, 351))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.PushButtonADDSecond = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonADDSecond.sizePolicy().hasHeightForWidth())
        self.PushButtonADDSecond.setSizePolicy(sizePolicy)
        self.PushButtonADDSecond.setObjectName("PushButtonADDSecond")
        self.verticalLayout_8.addWidget(self.PushButtonADDSecond)
        self.PushButtonMontageSecond = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonMontageSecond.sizePolicy().hasHeightForWidth())
        self.PushButtonMontageSecond.setSizePolicy(sizePolicy)
        self.PushButtonMontageSecond.setObjectName("PushButtonMontageSecond")
        self.verticalLayout_8.addWidget(self.PushButtonMontageSecond)
        self.PushButtonInputSecond = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonInputSecond.sizePolicy().hasHeightForWidth())
        self.PushButtonInputSecond.setSizePolicy(sizePolicy)
        self.PushButtonInputSecond.setObjectName("PushButtonInputSecond")
        self.verticalLayout_8.addWidget(self.PushButtonInputSecond)
        self.PushButtonDropSecond = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonDropSecond.sizePolicy().hasHeightForWidth())
        self.PushButtonDropSecond.setSizePolicy(sizePolicy)
        self.PushButtonDropSecond.setObjectName("PushButtonDropSecond")
        self.verticalLayout_8.addWidget(self.PushButtonDropSecond)
        self.PushButtonSwapAB = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSwapAB.sizePolicy().hasHeightForWidth())
        self.PushButtonSwapAB.setSizePolicy(sizePolicy)
        self.PushButtonSwapAB.setObjectName("PushButtonSwapAB")
        self.verticalLayout_8.addWidget(self.PushButtonSwapAB)
        self.PushButtonConcatenate = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonConcatenate.sizePolicy().hasHeightForWidth())
        self.PushButtonConcatenate.setSizePolicy(sizePolicy)
        self.PushButtonConcatenate.setObjectName("PushButtonConcatenate")
        self.verticalLayout_8.addWidget(self.PushButtonConcatenate)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 380, 551, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PushButtonPSIStatistical = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonPSIStatistical.sizePolicy().hasHeightForWidth())
        self.PushButtonPSIStatistical.setSizePolicy(sizePolicy)
        self.PushButtonPSIStatistical.setObjectName("PushButtonPSIStatistical")
        self.verticalLayout_3.addWidget(self.PushButtonPSIStatistical)
        self.PushButtonPSIContinuous = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonPSIContinuous.sizePolicy().hasHeightForWidth())
        self.PushButtonPSIContinuous.setSizePolicy(sizePolicy)
        self.PushButtonPSIContinuous.setObjectName("PushButtonPSIContinuous")
        self.verticalLayout_3.addWidget(self.PushButtonPSIContinuous)
        self.PushButtonLoadPSI = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonLoadPSI.sizePolicy().hasHeightForWidth())
        self.PushButtonLoadPSI.setSizePolicy(sizePolicy)
        self.PushButtonLoadPSI.setObjectName("PushButtonLoadPSI")
        self.verticalLayout_3.addWidget(self.PushButtonLoadPSI)
        self.PushButtonStatisticalMutualInformation = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonStatisticalMutualInformation.sizePolicy().hasHeightForWidth())
        self.PushButtonStatisticalMutualInformation.setSizePolicy(sizePolicy)
        self.PushButtonStatisticalMutualInformation.setObjectName("PushButtonStatisticalMutualInformation")
        self.verticalLayout_3.addWidget(self.PushButtonStatisticalMutualInformation)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 360, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1010, 200, 95, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PushButtonAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.PushButtonAdd.setObjectName("PushButtonAdd")
        self.verticalLayout_2.addWidget(self.PushButtonAdd)
        self.PushButtonDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.PushButtonDelete.setObjectName("PushButtonDelete")
        self.verticalLayout_2.addWidget(self.PushButtonDelete)
        self.PushButtonDeleteAll = QtWidgets.QPushButton(self.layoutWidget)
        self.PushButtonDeleteAll.setObjectName("PushButtonDeleteAll")
        self.verticalLayout_2.addWidget(self.PushButtonDeleteAll)
        self.PushButtonMovieLoad = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonMovieLoad.setGeometry(QtCore.QRect(620, 440, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonMovieLoad.setFont(font)
        self.PushButtonMovieLoad.setObjectName("PushButtonMovieLoad")
        self.PushButtonOrig = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonOrig.setGeometry(QtCore.QRect(30, 840, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonOrig.setFont(font)
        self.PushButtonOrig.setStyleSheet("background-color: lime")
        self.PushButtonOrig.setObjectName("PushButtonOrig")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 380, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.TextBrowserMovie = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserMovie.setGeometry(QtCore.QRect(610, 400, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TextBrowserMovie.setFont(font)
        self.TextBrowserMovie.setObjectName("TextBrowserMovie")
        self.PushButtonAddMovie = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonAddMovie.setGeometry(QtCore.QRect(910, 440, 93, 28))
        self.PushButtonAddMovie.setObjectName("PushButtonAddMovie")
        self.PushButtonDeleteMovie = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonDeleteMovie.setGeometry(QtCore.QRect(1010, 440, 93, 28))
        self.PushButtonDeleteMovie.setObjectName("PushButtonDeleteMovie")
        self.PushButtonMontageAdd = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonMontageAdd.setGeometry(QtCore.QRect(910, 360, 93, 28))
        self.PushButtonMontageAdd.setObjectName("PushButtonMontageAdd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuSave = QtWidgets.QMenu(self.menuFiles)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_fif = QtWidgets.QAction(MainWindow)
        self.actionSave_fif.setObjectName("actionSave_fif")
        self.actionSave_set = QtWidgets.QAction(MainWindow)
        self.actionSave_set.setObjectName("actionSave_set")
        self.menuSave.addAction(self.actionSave_fif)
        self.menuSave.addAction(self.actionSave_set)
        self.menuFiles.addAction(self.actionOpen)
        self.menuFiles.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        self.EEGFilesList.setCurrentRow(-1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EEG_files"))
        self.label_2.setText(_translate("MainWindow", "Montage file"))
        self.PushButtonDeleteMontage.setText(_translate("MainWindow", "Delete"))
        self.PushButtonRawPlot.setText(_translate("MainWindow", "RawPlot(mne)"))
        __sortingEnabled = self.InfoTable.isSortingEnabled()
        self.InfoTable.setSortingEnabled(False)
        self.InfoTable.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Data Information"))
        self.PushButtonPlotPW.setText(_translate("MainWindow", "PowerPlot(mne)"))
        self.PushButtonSaveFif.setText(_translate("MainWindow", "Save as .fif"))
        self.PushButtonSaveSet.setText(_translate("MainWindow", "Save as .set"))
        self.PushButtonADDOrg.setText(_translate("MainWindow", "0.EEGFiles_ADD"))
        self.PushButtonMontage.setText(_translate("MainWindow", "1.MontageFile_ADD"))
        self.PushButtonInput.setText(_translate("MainWindow", "2.Load_EEG (transform to raw object)"))
        self.label_3.setText(_translate("MainWindow", "Preprocessing"))
        self.PushButtonRename.setText(_translate("MainWindow", "3.Rename_Channels"))
        self.PushButtonReorder.setText(_translate("MainWindow", "3\'.Reorder_Channels"))
        self.PushButtonNoREF.setText(_translate("MainWindow", "4.Set_REF"))
        self.PushButtonFiltering.setText(_translate("MainWindow", "5.Filtering (+F)"))
        self.PushButtonResampling.setText(_translate("MainWindow", "6.Resampling (+R)"))
        self.PushButtonDrop.setText(_translate("MainWindow", "7.Drop_Channels"))
        self.PushButtonEOGO.setText(_translate("MainWindow", "7\'.Select_EOG"))
        self.PushButtonSM.setText(_translate("MainWindow", "8.Set_Montage"))
        self.PushButtonInterP.setText(_translate("MainWindow", "9.Interpolate_BAD"))
        self.PushButtonICA.setText(_translate("MainWindow", "10.Run_ICA"))
        self.PushButtonApplyICA.setText(_translate("MainWindow", "11.Apply_ICA"))
        self.label_6.setText(_translate("MainWindow", "HP_Preprocessing"))
        self.PushButtonSplit.setText(_translate("MainWindow", "*Split_Data"))
        self.PushButtonSelectEOG.setText(_translate("MainWindow", "*Select_EOG"))
        self.PushButtonSMHP.setText(_translate("MainWindow", "*Set_Montage"))
        self.PushButtonInterPHP.setText(_translate("MainWindow", "*Interpolate_BAD"))
        self.PushButtonAdjust.setText(_translate("MainWindow", "*Adjust_Algorithm (MATLAB) (+J)"))
        self.PushButtonEOGCorrect.setText(_translate("MainWindow", "*EOG_Correct (ICA with MNE) (+E)"))
        self.PushButtonCSD.setText(_translate("MainWindow", "*Csd_Apply (+C)"))
        self.PushButtonMerge.setText(_translate("MainWindow", "*Merge_Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PreProcessing"))
        self.PushButtonADDSecond.setText(_translate("MainWindow", "0.EEGFiles_ADD"))
        self.PushButtonMontageSecond.setText(_translate("MainWindow", "1.MontageFile_ADD"))
        self.PushButtonInputSecond.setText(_translate("MainWindow", "2.Load_EEG (transform to raw object)"))
        self.PushButtonDropSecond.setText(_translate("MainWindow", "3.Drop_Channels"))
        self.PushButtonSwapAB.setText(_translate("MainWindow", "3\'.Swap_AB"))
        self.PushButtonConcatenate.setText(_translate("MainWindow", "4.Concatenate_Data (for sync with movie)"))
        self.PushButtonPSIStatistical.setText(_translate("MainWindow", "5.Statistical_PSI"))
        self.PushButtonPSIContinuous.setText(_translate("MainWindow", "6.Continuous_PSI"))
        self.PushButtonLoadPSI.setText(_translate("MainWindow", "7.Continuous_PSI_Load"))
        self.PushButtonStatisticalMutualInformation.setText(_translate("MainWindow", "8.Statistical_Mutual_Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Analysis"))
        self.PushButtonAdd.setText(_translate("MainWindow", "Add"))
        self.PushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.PushButtonDeleteAll.setText(_translate("MainWindow", "Delete All"))
        self.PushButtonMovieLoad.setText(_translate("MainWindow", "Movie Load"))
        self.PushButtonOrig.setText(_translate("MainWindow", "RawPlot"))
        self.label_5.setText(_translate("MainWindow", "Movie file"))
        self.PushButtonAddMovie.setText(_translate("MainWindow", "Set"))
        self.PushButtonDeleteMovie.setText(_translate("MainWindow", "Delete"))
        self.PushButtonMontageAdd.setText(_translate("MainWindow", "Set"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_fif.setText(_translate("MainWindow", "Save (.fif)"))
        self.actionSave_set.setText(_translate("MainWindow", "Save (.set)"))
