# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_information_plot.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(914, 742)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(690, 700, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 20, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 50, 411, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(350, 80, 361, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(250, 110, 411, 16))
        self.label_4.setObjectName("label_4")
        self.PushButtonChangeTarget = QtWidgets.QPushButton(Dialog)
        self.PushButtonChangeTarget.setGeometry(QtCore.QRect(530, 495, 93, 28))
        self.PushButtonChangeTarget.setObjectName("PushButtonChangeTarget")
        self.LabelTarget = QtWidgets.QLabel(Dialog)
        self.LabelTarget.setGeometry(QtCore.QRect(390, 490, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelTarget.setFont(font)
        self.LabelTarget.setText("")
        self.LabelTarget.setObjectName("LabelTarget")
        self.PushButtonChangeSeed = QtWidgets.QPushButton(Dialog)
        self.PushButtonChangeSeed.setGeometry(QtCore.QRect(530, 445, 93, 28))
        self.PushButtonChangeSeed.setObjectName("PushButtonChangeSeed")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 450, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LabelSeed = QtWidgets.QLabel(Dialog)
        self.LabelSeed.setGeometry(QtCore.QRect(390, 440, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelSeed.setFont(font)
        self.LabelSeed.setText("")
        self.LabelSeed.setObjectName("LabelSeed")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(330, 500, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(60, 160, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 410, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(50, 200, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.LabelEnt = QtWidgets.QLabel(Dialog)
        self.LabelEnt.setGeometry(QtCore.QRect(100, 230, 711, 20))
        self.LabelEnt.setText("")
        self.LabelEnt.setObjectName("LabelEnt")
        self.PushButtonChangeEnt = QtWidgets.QPushButton(Dialog)
        self.PushButtonChangeEnt.setGeometry(QtCore.QRect(320, 190, 93, 28))
        self.PushButtonChangeEnt.setObjectName("PushButtonChangeEnt")
        self.PushButtonContinuousEntropyPlot = QtWidgets.QPushButton(Dialog)
        self.PushButtonContinuousEntropyPlot.setGeometry(QtCore.QRect(50, 350, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonContinuousEntropyPlot.setFont(font)
        self.PushButtonContinuousEntropyPlot.setStyleSheet("background-color: pink")
        self.PushButtonContinuousEntropyPlot.setObjectName("PushButtonContinuousEntropyPlot")
        self.DoubleSpinBoxWindowT = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxWindowT.setGeometry(QtCore.QRect(330, 261, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxWindowT.setFont(font)
        self.DoubleSpinBoxWindowT.setObjectName("DoubleSpinBoxWindowT")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(180, 270, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(180, 310, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(410, 270, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(410, 310, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.DoubleSpinBoxStrideT = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxStrideT.setGeometry(QtCore.QRect(330, 300, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxStrideT.setFont(font)
        self.DoubleSpinBoxStrideT.setObjectName("DoubleSpinBoxStrideT")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(180, 550, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.DoubleSpinBoxWindowTM = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxWindowTM.setGeometry(QtCore.QRect(330, 541, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxWindowTM.setFont(font)
        self.DoubleSpinBoxWindowTM.setObjectName("DoubleSpinBoxWindowTM")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(410, 550, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(180, 590, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.DoubleSpinBoxStrideTM = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxStrideTM.setGeometry(QtCore.QRect(330, 580, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxStrideTM.setFont(font)
        self.DoubleSpinBoxStrideTM.setObjectName("DoubleSpinBoxStrideTM")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(410, 590, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.PushButtonContinuousEntropyPlotM = QtWidgets.QPushButton(Dialog)
        self.PushButtonContinuousEntropyPlotM.setGeometry(QtCore.QRect(50, 630, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonContinuousEntropyPlotM.setFont(font)
        self.PushButtonContinuousEntropyPlotM.setStyleSheet("background-color: pink")
        self.PushButtonContinuousEntropyPlotM.setObjectName("PushButtonContinuousEntropyPlotM")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(860, 549, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(660, 589, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(560, 549, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(480, 410, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.DoubleSpinBoxWindowTML = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxWindowTML.setGeometry(QtCore.QRect(780, 540, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxWindowTML.setFont(font)
        self.DoubleSpinBoxWindowTML.setObjectName("DoubleSpinBoxWindowTML")
        self.PushButtonContinuousEntropyPlotML = QtWidgets.QPushButton(Dialog)
        self.PushButtonContinuousEntropyPlotML.setGeometry(QtCore.QRect(500, 630, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonContinuousEntropyPlotML.setFont(font)
        self.PushButtonContinuousEntropyPlotML.setStyleSheet("background-color: pink")
        self.PushButtonContinuousEntropyPlotML.setObjectName("PushButtonContinuousEntropyPlotML")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(170, 670, 731, 20))
        self.label_25.setObjectName("label_25")
        self.SpinBoxL = QtWidgets.QSpinBox(Dialog)
        self.SpinBoxL.setGeometry(QtCore.QRect(780, 580, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBoxL.setFont(font)
        self.SpinBoxL.setObjectName("SpinBoxL")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(860, 590, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Information Plot Mode"))
        self.label_2.setText(_translate("Dialog", "If you want to specify Range, register \"m_info\" event first."))
        self.label_3.setText(_translate("Dialog", "In that case, only the first event found is considered."))
        self.label_4.setText(_translate("Dialog", "If not specified, calculation is performed for all ranges."))
        self.PushButtonChangeTarget.setText(_translate("Dialog", "Change"))
        self.PushButtonChangeSeed.setText(_translate("Dialog", "Change"))
        self.label_5.setText(_translate("Dialog", "Seed："))
        self.label_6.setText(_translate("Dialog", "Target："))
        self.label_7.setText(_translate("Dialog", "- Information Entropy Continuous Plot -"))
        self.label_8.setText(_translate("Dialog", "- Mutual Information Entropy Continuous Plot -"))
        self.label_9.setText(_translate("Dialog", "Channels："))
        self.PushButtonChangeEnt.setText(_translate("Dialog", "Change"))
        self.PushButtonContinuousEntropyPlot.setText(_translate("Dialog", "Plot"))
        self.label_10.setText(_translate("Dialog", "Window_length："))
        self.label_11.setText(_translate("Dialog", "Stride_length："))
        self.label_12.setText(_translate("Dialog", "s"))
        self.label_13.setText(_translate("Dialog", "s"))
        self.label_14.setText(_translate("Dialog", "Window_length："))
        self.label_15.setText(_translate("Dialog", "s"))
        self.label_16.setText(_translate("Dialog", "Stride_length："))
        self.label_17.setText(_translate("Dialog", "s"))
        self.PushButtonContinuousEntropyPlotM.setText(_translate("Dialog", "Plot"))
        self.label_19.setText(_translate("Dialog", "s"))
        self.label_22.setText(_translate("Dialog", "Lag Nums："))
        self.label_23.setText(_translate("Dialog", "Lagged Window_length："))
        self.label_24.setText(_translate("Dialog", "- Lagged Mutual Information Continuous Plot -"))
        self.PushButtonContinuousEntropyPlotML.setText(_translate("Dialog", "Plot"))
        self.label_25.setText(_translate("Dialog", "The target is shifted based on \"m_info\", and MI is calculated for each lag window length for the number of lags."))
        self.label_21.setText(_translate("Dialog", "ケ"))
