# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_continuous_psi.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1190, 505)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: slateblue")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(670, 30, 431, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 60, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(70, 150, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(70, 190, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(70, 260, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(70, 345, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(70, 385, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(70, 470, 1041, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.LabelProgress = QtWidgets.QLabel(Dialog)
        self.LabelProgress.setGeometry(QtCore.QRect(120, 440, 741, 21))
        self.LabelProgress.setText("")
        self.LabelProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelProgress.setObjectName("LabelProgress")
        self.DoubleSpinBoxWindowTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxWindowTime.setGeometry(QtCore.QRect(240, 105, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxWindowTime.setFont(font)
        self.DoubleSpinBoxWindowTime.setObjectName("DoubleSpinBoxWindowTime")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(320, 115, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.DoubleSpinBoxStrideTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxStrideTime.setGeometry(QtCore.QRect(240, 145, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxStrideTime.setFont(font)
        self.DoubleSpinBoxStrideTime.setObjectName("DoubleSpinBoxStrideTime")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(320, 155, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(450, 120, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(500, 110, 111, 16))
        self.label_5.setStyleSheet("background-color: green")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(500, 90, 131, 16))
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(540, 130, 111, 16))
        self.label_13.setStyleSheet("background-color: green")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(580, 150, 111, 16))
        self.label_14.setStyleSheet("background-color: green")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(650, 110, 151, 16))
        self.label_16.setObjectName("label_16")
        self.PushButtonChangeChannels = QtWidgets.QPushButton(Dialog)
        self.PushButtonChangeChannels.setGeometry(QtCore.QRect(260, 185, 161, 28))
        self.PushButtonChangeChannels.setStyleSheet("background-color: lavender")
        self.PushButtonChangeChannels.setObjectName("PushButtonChangeChannels")
        self.LabelSeed = QtWidgets.QLabel(Dialog)
        self.LabelSeed.setGeometry(QtCore.QRect(90, 230, 1011, 20))
        self.LabelSeed.setStyleSheet("color: purple")
        self.LabelSeed.setText("")
        self.LabelSeed.setObjectName("LabelSeed")
        self.LabelTarget = QtWidgets.QLabel(Dialog)
        self.LabelTarget.setGeometry(QtCore.QRect(90, 300, 1011, 20))
        self.LabelTarget.setStyleSheet("color: purple")
        self.LabelTarget.setText("")
        self.LabelTarget.setObjectName("LabelTarget")
        self.DoubleSpinBoxFreqMin = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxFreqMin.setGeometry(QtCore.QRect(290, 340, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxFreqMin.setFont(font)
        self.DoubleSpinBoxFreqMin.setObjectName("DoubleSpinBoxFreqMin")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(370, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.DoubleSpinBoxFreqMax = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxFreqMax.setGeometry(QtCore.QRect(450, 340, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxFreqMax.setFont(font)
        self.DoubleSpinBoxFreqMax.setObjectName("DoubleSpinBoxFreqMax")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(530, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(410, 350, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.DoubleSpinBoxRangeStep = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxRangeStep.setGeometry(QtCore.QRect(230, 380, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxRangeStep.setFont(font)
        self.DoubleSpinBoxRangeStep.setObjectName("DoubleSpinBoxRangeStep")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(310, 390, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.PushButtonResult = QtWidgets.QPushButton(Dialog)
        self.PushButtonResult.setGeometry(QtCore.QRect(780, 370, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.PushButtonResult.setFont(font)
        self.PushButtonResult.setStyleSheet("background-color: gold")
        self.PushButtonResult.setObjectName("PushButtonResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Continuous_PSI Calculation"))
        self.label_2.setText(_translate("Dialog", "-It takes a lot of calculation, but you can calculate all PSI first-"))
        self.label_3.setText(_translate("Dialog", "●Seed raw： this one"))
        self.label_6.setText(_translate("Dialog", "●Window time："))
        self.label_7.setText(_translate("Dialog", "●Stride time："))
        self.label_8.setText(_translate("Dialog", "●Seed Channels："))
        self.label_9.setText(_translate("Dialog", "●Target Channels："))
        self.label_12.setText(_translate("Dialog", "●Frequency Range："))
        self.label_24.setText(_translate("Dialog", "●Range Step："))
        self.label_10.setText(_translate("Dialog", "s"))
        self.label_11.setText(_translate("Dialog", "s"))
        self.label_4.setText(_translate("Dialog", "例："))
        self.label_15.setText(_translate("Dialog", "|< Window time >|"))
        self.label_16.setText(_translate("Dialog", "|<    >| Stride time"))
        self.PushButtonChangeChannels.setText(_translate("Dialog", "ChangeChannels"))
        self.label_17.setText(_translate("Dialog", "Hz"))
        self.label_18.setText(_translate("Dialog", "Hz"))
        self.label_19.setText(_translate("Dialog", "～"))
        self.label_20.setText(_translate("Dialog", "Hz"))
        self.PushButtonResult.setText(_translate("Dialog", "Calculation_and_save_the_results"))
