# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_auto_peak_detect.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 556)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 400, 62, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SpinBoxOrder = QtWidgets.QSpinBox(Dialog)
        self.SpinBoxOrder.setGeometry(QtCore.QRect(90, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinBoxOrder.setFont(font)
        self.SpinBoxOrder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SpinBoxOrder.setObjectName("SpinBoxOrder")
        self.PushButtonDetect = QtWidgets.QPushButton(Dialog)
        self.PushButtonDetect.setGeometry(QtCore.QRect(40, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonDetect.setFont(font)
        self.PushButtonDetect.setStyleSheet("background-color: azure")
        self.PushButtonDetect.setObjectName("PushButtonDetect")
        self.PushButtonClearResult = QtWidgets.QPushButton(Dialog)
        self.PushButtonClearResult.setGeometry(QtCore.QRect(170, 470, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PushButtonClearResult.setFont(font)
        self.PushButtonClearResult.setStyleSheet("background-color: azure")
        self.PushButtonClearResult.setObjectName("PushButtonClearResult")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 400, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.SpinBoxPreFilter = QtWidgets.QSpinBox(Dialog)
        self.SpinBoxPreFilter.setGeometry(QtCore.QRect(310, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinBoxPreFilter.setFont(font)
        self.SpinBoxPreFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SpinBoxPreFilter.setObjectName("SpinBoxPreFilter")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(400, 410, 131, 16))
        self.label_4.setObjectName("label_4")
        self.LabelComment = QtWidgets.QLabel(Dialog)
        self.LabelComment.setGeometry(QtCore.QRect(300, 480, 231, 16))
        self.LabelComment.setText("")
        self.LabelComment.setObjectName("LabelComment")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 511, 331))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(250, 29, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(320, 20, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(320, 520, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "AutoPeakDetect"))
        self.label_2.setText(_translate("Dialog", "order"))
        self.PushButtonDetect.setText(_translate("Dialog", "Detect"))
        self.PushButtonClearResult.setText(_translate("Dialog", "Clear Result"))
        self.label_3.setText(_translate("Dialog", "PreFiltering"))
        self.label_4.setText(_translate("Dialog", "(median filter order)"))
        self.label_5.setText(_translate("Dialog", "Select："))
