# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_eegview_focus.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1725, 980)
        Dialog.setStyleSheet("background-color: white")
        self.graphicsView = GraphicsLayoutWidget(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1711, 861))
        self.graphicsView.setMouseTracking(False)
        self.graphicsView.setObjectName("graphicsView")
        self.PushButtonEvents = QtWidgets.QPushButton(Dialog)
        self.PushButtonEvents.setGeometry(QtCore.QRect(10, 950, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonEvents.setFont(font)
        self.PushButtonEvents.setStyleSheet("background-color: rgb(229, 204, 255)")
        self.PushButtonEvents.setObjectName("PushButtonEvents")
        self.PushButtonEventsEdit = QtWidgets.QPushButton(Dialog)
        self.PushButtonEventsEdit.setGeometry(QtCore.QRect(140, 950, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonEventsEdit.setFont(font)
        self.PushButtonEventsEdit.setStyleSheet("background-color: rgb(229, 204, 255)")
        self.PushButtonEventsEdit.setObjectName("PushButtonEventsEdit")
        self.PushButtonOption = QtWidgets.QPushButton(Dialog)
        self.PushButtonOption.setGeometry(QtCore.QRect(10, 920, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonOption.setFont(font)
        self.PushButtonOption.setStyleSheet("background-color: rgb(229, 204, 255)")
        self.PushButtonOption.setObjectName("PushButtonOption")
        self.verticalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1710, 0, 16, 781))
        self.verticalScrollBar.setStyleSheet("background-color: gray")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(140, 920, 1551, 31))
        self.horizontalScrollBar.setStyleSheet("background-color: gray")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.graphicsView_sub = GraphicsLayoutWidget(Dialog)
        self.graphicsView_sub.setGeometry(QtCore.QRect(0, 850, 1711, 81))
        self.graphicsView_sub.setObjectName("graphicsView_sub")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(1500, 950, 211, 32))
        self.buttonBox.setStyleSheet("background-color: pink")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(1290, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: pink")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.PushButtonPlayWithVideo = QtWidgets.QPushButton(Dialog)
        self.PushButtonPlayWithVideo.setGeometry(QtCore.QRect(830, 950, 131, 28))
        self.PushButtonPlayWithVideo.setStyleSheet("background-color: lemonchiffon")
        self.PushButtonPlayWithVideo.setObjectName("PushButtonPlayWithVideo")
        self.PushButtonPSISettings = QtWidgets.QPushButton(Dialog)
        self.PushButtonPSISettings.setGeometry(QtCore.QRect(270, 950, 131, 28))
        self.PushButtonPSISettings.setStyleSheet("background-color: rgb(229, 204, 255)")
        self.PushButtonPSISettings.setObjectName("PushButtonPSISettings")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(980, 960, 171, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.TextBrowserBad = QtWidgets.QTextBrowser(Dialog)
        self.TextBrowserBad.setGeometry(QtCore.QRect(1160, 950, 256, 31))
        self.TextBrowserBad.setObjectName("TextBrowserBad")
        self.PushButtonSpectogram = QtWidgets.QPushButton(Dialog)
        self.PushButtonSpectogram.setGeometry(QtCore.QRect(550, 950, 131, 28))
        self.PushButtonSpectogram.setStyleSheet("background-color: lavender")
        self.PushButtonSpectogram.setObjectName("PushButtonSpectogram")
        self.PushButtonInformationPlot = QtWidgets.QPushButton(Dialog)
        self.PushButtonInformationPlot.setGeometry(QtCore.QRect(690, 950, 131, 28))
        self.PushButtonInformationPlot.setStyleSheet("background-color: lavender")
        self.PushButtonInformationPlot.setObjectName("PushButtonInformationPlot")
        self.graphicsView_sub.raise_()
        self.graphicsView.raise_()
        self.PushButtonEvents.raise_()
        self.PushButtonEventsEdit.raise_()
        self.PushButtonOption.raise_()
        self.verticalScrollBar.raise_()
        self.horizontalScrollBar.raise_()
        self.buttonBox.raise_()
        self.label.raise_()
        self.PushButtonPlayWithVideo.raise_()
        self.PushButtonPSISettings.raise_()
        self.label_2.raise_()
        self.TextBrowserBad.raise_()
        self.PushButtonSpectogram.raise_()
        self.PushButtonInformationPlot.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PushButtonEvents.setText(_translate("Dialog", "Events_check"))
        self.PushButtonEventsEdit.setText(_translate("Dialog", "Events_edit"))
        self.PushButtonOption.setText(_translate("Dialog", "Option"))
        self.PushButtonPlayWithVideo.setText(_translate("Dialog", "Play with Video"))
        self.PushButtonPSISettings.setText(_translate("Dialog", "InstantPSI_settings"))
        self.label_2.setText(_translate("Dialog", "Bad channels (\"b\" click)"))
        self.PushButtonSpectogram.setText(_translate("Dialog", "Spectrogram"))
        self.PushButtonInformationPlot.setText(_translate("Dialog", "Information_Plot"))
from pyqtgraph import GraphicsLayoutWidget
