# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_psi_statistical.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 1000)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(490, 970, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: slateblue")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ScrollAreaSeed = QtWidgets.QScrollArea(Dialog)
        self.ScrollAreaSeed.setGeometry(QtCore.QRect(280, 70, 381, 161))
        self.ScrollAreaSeed.setStyleSheet("")
        self.ScrollAreaSeed.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollAreaSeed.setWidgetResizable(True)
        self.ScrollAreaSeed.setObjectName("ScrollAreaSeed")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ScrollAreaSeed.setWidget(self.scrollAreaWidgetContents)
        self.ComboBoxTarget = QtWidgets.QComboBox(Dialog)
        self.ComboBoxTarget.setGeometry(QtCore.QRect(180, 245, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ComboBoxTarget.setFont(font)
        self.ComboBoxTarget.setObjectName("ComboBoxTarget")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ScrollAreaTarget = QtWidgets.QScrollArea(Dialog)
        self.ScrollAreaTarget.setGeometry(QtCore.QRect(280, 290, 381, 161))
        self.ScrollAreaTarget.setStyleSheet("")
        self.ScrollAreaTarget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollAreaTarget.setWidgetResizable(True)
        self.ScrollAreaTarget.setObjectName("ScrollAreaTarget")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 379, 159))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.ScrollAreaTarget.setWidget(self.scrollAreaWidgetContents_2)
        self.DoubleSpinBoxWindowTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxWindowTime.setGeometry(QtCore.QRect(220, 465, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxWindowTime.setFont(font)
        self.DoubleSpinBoxWindowTime.setObjectName("DoubleSpinBoxWindowTime")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 470, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(530, 820, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 510, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 570, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.LabelSeed = QtWidgets.QLabel(Dialog)
        self.LabelSeed.setGeometry(QtCore.QRect(40, 540, 611, 20))
        self.LabelSeed.setText("")
        self.LabelSeed.setObjectName("LabelSeed")
        self.LabelTarget = QtWidgets.QLabel(Dialog)
        self.LabelTarget.setGeometry(QtCore.QRect(40, 605, 611, 20))
        self.LabelTarget.setText("")
        self.LabelTarget.setObjectName("LabelTarget")
        self.PushButtonChangeChannels = QtWidgets.QPushButton(Dialog)
        self.PushButtonChangeChannels.setGeometry(QtCore.QRect(220, 505, 161, 28))
        self.PushButtonChangeChannels.setStyleSheet("background-color: lavender")
        self.PushButtonChangeChannels.setObjectName("PushButtonChangeChannels")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(100, 210, 101, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(100, 430, 101, 16))
        self.label_11.setObjectName("label_11")
        self.LabelComment = QtWidgets.QLabel(Dialog)
        self.LabelComment.setGeometry(QtCore.QRect(320, 470, 391, 16))
        self.LabelComment.setObjectName("LabelComment")
        self.LabelSeedCount = QtWidgets.QLabel(Dialog)
        self.LabelSeedCount.setGeometry(QtCore.QRect(200, 210, 61, 16))
        self.LabelSeedCount.setText("")
        self.LabelSeedCount.setObjectName("LabelSeedCount")
        self.LabelTargetCount = QtWidgets.QLabel(Dialog)
        self.LabelTargetCount.setGeometry(QtCore.QRect(200, 430, 61, 16))
        self.LabelTargetCount.setText("")
        self.LabelTargetCount.setObjectName("LabelTargetCount")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(30, 635, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 945, 551, 16))
        self.label_14.setObjectName("label_14")
        self.ScrollAreaFreqRange = QtWidgets.QScrollArea(Dialog)
        self.ScrollAreaFreqRange.setGeometry(QtCore.QRect(280, 635, 261, 111))
        self.ScrollAreaFreqRange.setStyleSheet("")
        self.ScrollAreaFreqRange.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollAreaFreqRange.setWidgetResizable(True)
        self.ScrollAreaFreqRange.setObjectName("ScrollAreaFreqRange")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 259, 109))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.ScrollAreaFreqRange.setWidget(self.scrollAreaWidgetContents_3)
        self.PushButtonAddRange = QtWidgets.QPushButton(Dialog)
        self.PushButtonAddRange.setGeometry(QtCore.QRect(560, 635, 101, 31))
        self.PushButtonAddRange.setStyleSheet("background-color: linen")
        self.PushButtonAddRange.setObjectName("PushButtonAddRange")
        self.PushButtonClearRange = QtWidgets.QPushButton(Dialog)
        self.PushButtonClearRange.setGeometry(QtCore.QRect(560, 675, 101, 31))
        self.PushButtonClearRange.setStyleSheet("background-color: linen")
        self.PushButtonClearRange.setObjectName("PushButtonClearRange")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(30, 665, 71, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(110, 665, 131, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(110, 685, 131, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(110, 705, 131, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(110, 725, 131, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(110, 745, 151, 16))
        self.label_20.setObjectName("label_20")
        self.PushButtonResult = QtWidgets.QPushButton(Dialog)
        self.PushButtonResult.setGeometry(QtCore.QRect(60, 855, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonResult.setFont(font)
        self.PushButtonResult.setStyleSheet("background-color: gold")
        self.PushButtonResult.setObjectName("PushButtonResult")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(300, 775, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.ComboBoxFDR = QtWidgets.QComboBox(Dialog)
        self.ComboBoxFDR.setGeometry(QtCore.QRect(180, 920, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ComboBoxFDR.setFont(font)
        self.ComboBoxFDR.setObjectName("ComboBoxFDR")
        self.ComboBoxFDR.addItem("")
        self.ComboBoxFDR.addItem("")
        self.SpinBoxPermTimes = QtWidgets.QSpinBox(Dialog)
        self.SpinBoxPermTimes.setGeometry(QtCore.QRect(520, 770, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBoxPermTimes.setFont(font)
        self.SpinBoxPermTimes.setObjectName("SpinBoxPermTimes")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(620, 785, 62, 15))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(30, 815, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(300, 815, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.DoubleSpinBoxRangeStep = QtWidgets.QDoubleSpinBox(Dialog)
        self.DoubleSpinBoxRangeStep.setGeometry(QtCore.QRect(450, 810, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBoxRangeStep.setFont(font)
        self.DoubleSpinBoxRangeStep.setObjectName("DoubleSpinBoxRangeStep")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(340, 880, 341, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.LabelProgress = QtWidgets.QLabel(Dialog)
        self.LabelProgress.setGeometry(QtCore.QRect(370, 860, 241, 20))
        self.LabelProgress.setText("")
        self.LabelProgress.setObjectName("LabelProgress")
        self.PushButtonResultPlot = QtWidgets.QPushButton(Dialog)
        self.PushButtonResultPlot.setGeometry(QtCore.QRect(70, 965, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonResultPlot.setFont(font)
        self.PushButtonResultPlot.setStyleSheet("background-color: pink")
        self.PushButtonResultPlot.setObjectName("PushButtonResultPlot")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 920, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.PushButtonResultSave = QtWidgets.QPushButton(Dialog)
        self.PushButtonResultSave.setGeometry(QtCore.QRect(210, 965, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PushButtonResultSave.setFont(font)
        self.PushButtonResultSave.setStyleSheet("background-color:pink")
        self.PushButtonResultSave.setObjectName("PushButtonResultSave")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(300, 475, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PSI Calculation"))
        self.label_2.setText(_translate("Dialog", "●Seed raw： this one"))
        self.label_3.setText(_translate("Dialog", "●Target raw："))
        self.label_4.setText(_translate("Dialog", "： Seed events name："))
        self.label_5.setText(_translate("Dialog", "： Target events name："))
        self.label_6.setText(_translate("Dialog", "●Window time："))
        self.label_7.setText(_translate("Dialog", "Hz"))
        self.label_8.setText(_translate("Dialog", "●Seed Channels："))
        self.label_9.setText(_translate("Dialog", "●Target Channels："))
        self.PushButtonChangeChannels.setText(_translate("Dialog", "ChangeChannels"))
        self.label_10.setText(_translate("Dialog", "Events Count:"))
        self.label_11.setText(_translate("Dialog", "Events Count:"))
        self.LabelComment.setText(_translate("Dialog", "For statistical testing, keep the number of events the same."))
        self.label_12.setText(_translate("Dialog", "●Frequency Range："))
        self.label_14.setText(_translate("Dialog", "If the Frequency Range is increased, the FDR correction will be applied accordingly."))
        self.PushButtonAddRange.setText(_translate("Dialog", "AddRange"))
        self.PushButtonClearRange.setText(_translate("Dialog", "Clear"))
        self.label_15.setText(_translate("Dialog", "reference:"))
        self.label_16.setText(_translate("Dialog", "δ range: 0.5 ～ 4"))
        self.label_17.setText(_translate("Dialog", "θ range: 4 ～ 8"))
        self.label_18.setText(_translate("Dialog", "α range: 8 ～ 13"))
        self.label_19.setText(_translate("Dialog", "β range: 13 ～ 30"))
        self.label_20.setText(_translate("Dialog", "γ range: 30 ～     Hz"))
        self.PushButtonResult.setText(_translate("Dialog", "Calculation"))
        self.label_21.setText(_translate("Dialog", "●Permutation Times："))
        self.ComboBoxFDR.setItemText(0, _translate("Dialog", "Yes"))
        self.ComboBoxFDR.setItemText(1, _translate("Dialog", "No"))
        self.label_22.setText(_translate("Dialog", "times"))
        self.label_23.setText(_translate("Dialog", "●Margin： 1-1s"))
        self.label_24.setText(_translate("Dialog", "●Range Step："))
        self.PushButtonResultPlot.setText(_translate("Dialog", "PlotResult"))
        self.label_13.setText(_translate("Dialog", "FDR Correction："))
        self.PushButtonResultSave.setText(_translate("Dialog", "SaveResult"))
        self.label_25.setText(_translate("Dialog", "s"))
